# Etape 3 - Publication

## Objectifs

-   Faciliter la découvrabilité et l'usage des données à travers le renseignement précis des métadonnées et de la licence

<!-- -->

-   Publier les données sur une plateforme adaptée

## Contenu

Une fois les données mise en qualité, elles sont prêtes pour la publication sur une plateforme de données ouvertes.

1.  En complément des éléments de qualité interne des données, quelques vérifications complémentaires peuvent s'avérer nécessaire : elles sont listées dans la [liste des points de contrôle externe](https://nextcloud.datactivist.coop/s/NiwgaxjSyjcDFYT).

2.  Il faut ensuite préparer la publication en préparant la description des données ([métadonnées descriptives)](https://nextcloud.datactivist.coop/s/RpjF9znR85sa4H8).

3.  Le choix de la plateforme de publication peut s'avérer nécessaire : pour toutes les données qui concernent les transports ce sera sur transports.data.gouv, dans le cas où la structure qui va ouvrir ses données est impliquées dans un projet de plateforme de données ouvertes, la publication se fera sur celle-ci et, dans tous les autres cas, elle se fera sur data.gouv.fr. 

## Ressources

-   [Fiches de métadonnées](https://docs.google.com/document/d/1P-nJ4tSjx5_OCdBLfkRfglnOc-YBbAQnCA_xMf0_Qcc/edit?usp=sharing)

-   [Documentation de data.gouv.fr](https://doc.data.gouv.fr/) :

    -   [Créer un compte](https://doc.data.gouv.fr/gestion-du-compte/creer-un-compte/)

    -   [Publier un jeu de données](https://doc.data.gouv.fr/jeux-de-donnees/publier-un-jeu-de-donnees/)

    -   [Créer une organisation](https://doc.data.gouv.fr/organisations/creer-une-organisation/)
