# Pré-requis - diagnostic

## Objectifs

-   Recruter des participants

-   Evaluer la maturité des acteurs

-   Recenser les données qui pourraient être partagées ou ouvertes

## Contenu

La première étape vise à bien connaître les membres du MIX afin de comprendre leurs missions et leurs motivations au sein du MIX sur le sujet des données.

Deux grands types d'acteurs peuvent être identifiés :

-   Les producteurs de données

-   Les réutilisateurs de données

L\'identification des acteurs doit aussi permettre de mesurer leur niveau de maturité, d\'identifier les freins éventuels et les éléments de facilitation qui peuvent exister. 

Pour lancer la démarche de challenge data, une première série d'actions préparatoires a été menée :

-   Organisation d'un [webinaire de présentation](https://nextcloud.datactivist.coop/s/AZYDqQiYeRNBABo).

-   [Entretiens](https://nextcloud.datactivist.coop/s/iYcJd46nPPPc72K) avec les participants afin de comprendre, en amont, leur contexte et leurs attentes.

## Ressources

-   [Cartographie des acteurs du MIX](https://airtable.com/shrr9nE7E0gMOR0uR)

-   [Catalogue de données](https://airtable.com/shri9tug2a9KgnNAz) (identifiées lors du Challenge data)
